apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wp2-clearing-service
  namespace: test-project
  labels:
    app: wp2-clearing-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wp2-clearing-service

  template:
    metadata:
      labels:
        app: wp2-clearing-service
    spec:

      containers:

        - name: wp2-clearing-service
          image: acrtestproject.azurecr.io/clearing-service:latest
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: wp2-clearing-service-service
  namespace: test-project
  labels:
    app: wp2-clearing-service
spec:
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000
  selector:
    app: wp2-clearing-service
  type: LoadBalancer